---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
      - name: Get clickhouse distrib
        ansible.builtin.get_url:
          url: "https://packages.clickhouse.com/deb/pool/stable/{{ item }}_{{ clickhouse_version }}_all.deb"
          dest: "./{{ item }}-{{ clickhouse_version }}.deb"
        with_items: "{{ clickhouse_packages }}"
      rescue:
      - name: Get clickhouse distrib (rescue)
        ansible.builtin.get_url:
          url: "https://packages.clickhouse.com/deb/pool/stable/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
          dest: "./clickhouse-common-static-{{ clickhouse_version }}.deb"
    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        deb: "{{ item }}-{{ clickhouse_version }}.deb"
      with_items: "{{ clickhouse_packages }}" 
      notify: Start clickhouse service
    - name: Flush handlers if possible
      ansible.builtin.meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
